services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - composer-cache:/tmp/composer
    environment:
      - COMPOSER_CACHE_DIR=/tmp/composer

volumes:
  composer-cache:
